import type { PantryItem } from './types';
import { subDays, addDays } from 'date-fns';

const today = new Date();

export const mockPantryItems: Omit<PantryItem, 'id'>[] = [
  {
    name: 'Organic Bananas',
    category: 'Fruit',
    quantity: 3,
    unit: 'piece',
    purchaseDate: subDays(today, 2).toISOString(),
    expiryDate: addDays(today, 3).toISOString(),
    riskClass: 'High',
    riskScore: 0.85,
  },
  {
    name: 'Avocados',
    category: 'Fruit',
    quantity: 2,
    unit: 'piece',
    purchaseDate: subDays(today, 3).toISOString(),
    expiryDate: addDays(today, 1).toISOString(),
    riskClass: 'High',
    riskScore: 0.95,
  },
  {
    name: 'Whole Milk',
    category: 'Dairy',
    quantity: 1,
    unit: 'L',
    purchaseDate: subDays(today, 5).toISOString(),
    expiryDate: addDays(today, 5).toISOString(),
    riskClass: 'Medium',
    riskScore: 0.6,
  },
  {
    name: 'Sourdough Loaf',
    category: 'Bakery',
    quantity: 1,
    unit: 'piece',
    purchaseDate: subDays(today, 1).toISOString(),
    expiryDate: addDays(today, 4).toISOString(),
    riskClass: 'Medium',
    riskScore: 0.5,
  },
  {
    name: 'Spinach',
    category: 'Vegetable',
    quantity: 1,
    unit: 'pack',
    purchaseDate: subDays(today, 4).toISOString(),
    expiryDate: addDays(today, 2).toISOString(),
    riskClass: 'High',
    riskScore: 0.9,
  },
  {
    name: 'Free-range Eggs',
    category: 'Dairy',
    quantity: 8,
    unit: 'piece',
    purchaseDate: subDays(today, 10).toISOString(),
    expiryDate: addDays(today, 12).toISOString(),
    riskClass: 'Low',
    riskScore: 0.2,
  },
  {
    name: 'Chicken Thighs',
    category: 'Meat',
    quantity: 1,
    unit: 'pack',
    purchaseDate: subDays(today, 1).toISOString(),
    expiryDate: addDays(today, 6).toISOString(),
    riskClass: 'Low',
    riskScore: 0.3,
  },
  {
    name: 'Canned Tomatoes',
    category: 'Pantry',
    quantity: 4,
    unit: 'pack',
    purchaseDate: subDays(today, 30).toISOString(),
    expiryDate: addDays(today, 300).toISOString(),
    riskClass: 'Low',
    riskScore: 0.01,
  },
];
